# Site settings
name: Less Or More
email: 1028764968@qq.com
author:pkx10086
url: https://github_username.github.io
resume_site: github_pkx10086/github_pkx10086.github.io
github: https://github.com/github_pkx10086
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 潘凯旋;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: pkx10086

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

